version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: films
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - postgres
    depends_on: 
      - postgres

volumes:
  pgdata:
    driver: local